language: python
python:
  - 2.7

before_install:
  - pip install -U pip
  - pip install -U setuptools

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - coverage run --source=wechat_api setup.py test
  - coverage run --source=enterprise_api setup.py test

after_success:
- coveralls
